# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ConceptTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('copyright', models.CharField(max_length=300)),
                ('copyright_en', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('description_en', models.CharField(max_length=300)),
                ('contentSlots', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True)),
                ('description_en', models.CharField(max_length=250, null=True)),
                ('filename', models.CharField(default='', max_length=100, null=True)),
                ('file', models.FileField(max_length=500, null=True, upload_to='C:\\Users\\Manca\\IOI_konceptneTable\\KonceptneTable\\app/konceptneTable/static/konceptneTable/media/content/')),
                ('slot', models.IntegerField(default=0)),
                ('newSlot', models.IntegerField(default=0)),
                ('isImage', models.BooleanField(choices=[(True, 'Slika/Fotografija'), (False, 'Video')], default=True)),
                ('autoplay', models.BooleanField(default=False)),
                ('conceptTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konceptneTable.ConceptTable')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='conceptTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='konceptneTable.ConceptTable'),
        ),
    ]
