# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konceptneTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpiece',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='C:/Users/Manca/IOI_konceptneTable/concept-tables/app/konceptneTable/static/konceptneTable/media/content/'),
        ),
    ]
